[package]
name = "modules"
version = "0.1.0"
authors = ["elpinal"]
edition = "2018"

[dependencies]
colored = "1.7"
failure = "0.1.3"
structopt = "0.2"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
